### ISSUE TITLE
As `rclcpp::executor::FutureReturnCode::SUCCESS` was deprecated and need to use `rclcpp::FutureReturnCode::SUCCESS` 

### ISSUE THREAD

**Issue by surfertas** [fmrico/nav2_test_utils#1]
@fmrico per this [PR](https://github.com/ros2/rclcpp/pull/1327/files#diff-5560cc69598dae75afc60cfbb060f8f0a2a51be818d8f4bdb7cd38a6b69a71c5L48) `rclcpp::executor::FutureReturnCode` has been deprecated.

Need to change to `rclcpp::FutureReturnCode::SUCCESS` at

https://github.com/fmrico/nav2_test_utils/blob/2d4049cbe46afbd1ad469cdbac172c563eb99bee/src/nav2_client_util.cpp#L72

This is referenced in the [Dynamic Object Following](https://navigation.ros.org/tutorials/docs/navigation2_dynamic_point_following.html) tutorial.

I can open a PR if needed.

**Comment by fmrico** [comment]
Hi @surfertas 

Yes, open a PR to fix this.

Thanks!! ;)

**Comment by surfertas** [comment]
Understood. Will complete this over the next few days.
